"""
enrichment.py

Hand-verified enrichment data for the highest-priority / best-documented hash
formats in HashFox. Keyed by hashcat_mode.

Every field here is something that is independently, publicly documented
(hashcat wiki, John the Ripper docs/source, RFCs, vendor docs) -- not
guessed. If a field isn't confidently verifiable for a given format it is
simply omitted here, and the generator leaves it as null / [] in the final
record.

john_format values are John the Ripper --format= names taken from John's own
documented format list (john --list=formats). Do not add a john_format for a
mode unless it's a real, current John format name.
"""

ENRICHMENT = {
    # ---- MD4 ----
    900: {
        "category": "raw_hash",
        "john_format": "raw-md4",
        "length": 32,
        "min_length": 32,
        "max_length": 32,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{32}$",
        "salted": False,
        "security_level": "very_low",
        "description": "Unsalted MD4 digest. Cryptographically broken; trivially brute-forced or rainbow-tabled.",
        "common_usage": ["legacy protocols", "some older CMS/auth systems"],
        "recommended_attack": ["wordlist+rules", "mask_attack", "rainbow_table"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- MD5 ----
    0: {
        "category": "raw_hash",
        "john_format": "raw-md5",
        "length": 32,
        "min_length": 32,
        "max_length": 32,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{32}$",
        "salted": False,
        "security_level": "very_low",
        "description": "Unsalted MD5 digest. Fast to compute, no salt, widely rainbow-tabled.",
        "common_usage": ["legacy password storage", "checksums (non-security use)"],
        "recommended_attack": ["wordlist+rules", "mask_attack", "rainbow_table"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- SHA1 ----
    100: {
        "category": "raw_hash",
        "john_format": "raw-sha1",
        "length": 40,
        "min_length": 40,
        "max_length": 40,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{40}$",
        "salted": False,
        "security_level": "very_low",
        "description": "Unsalted SHA-1 digest. Deprecated for security use; fast GPU cracking, rainbow-tabled.",
        "common_usage": ["legacy password storage", "git object hashing (non-security use)"],
        "recommended_attack": ["wordlist+rules", "mask_attack", "rainbow_table"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- SHA2-224 ----
    1300: {
        "category": "raw_hash",
        "john_format": "raw-sha224",
        "length": 56,
        "min_length": 56,
        "max_length": 56,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{56}$",
        "salted": False,
        "security_level": "low",
        "description": "Unsalted SHA-224 digest. Rarely used for password storage directly.",
        "common_usage": ["checksums", "some embedded/legacy systems"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- SHA2-256 ----
    1400: {
        "category": "raw_hash",
        "john_format": "raw-sha256",
        "length": 64,
        "min_length": 64,
        "max_length": 64,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{64}$",
        "salted": False,
        "security_level": "low",
        "description": "Unsalted SHA-256 digest. No salt/KDF means it is still fast to brute-force despite SHA-256 being cryptographically strong.",
        "common_usage": ["legacy password storage", "checksums", "blockchain"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- SHA2-384 ----
    10800: {
        "category": "raw_hash",
        "john_format": "raw-sha384",
        "length": 96,
        "min_length": 96,
        "max_length": 96,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{96}$",
        "salted": False,
        "security_level": "low",
        "description": "Unsalted SHA-384 digest.",
        "common_usage": ["checksums", "some TLS/cert tooling"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- SHA2-512 ----
    1700: {
        "category": "raw_hash",
        "john_format": "raw-sha512",
        "length": 128,
        "min_length": 128,
        "max_length": 128,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{128}$",
        "salted": False,
        "security_level": "low",
        "description": "Unsalted SHA-512 digest.",
        "common_usage": ["legacy password storage", "checksums"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- LM ----
    3000: {
        "category": "windows",
        "john_format": "lm",
        "length": 16,
        "min_length": 16,
        "max_length": 16,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{16}$",
        "salted": False,
        "security_level": "very_low",
        "description": "Windows LAN Manager hash. Uppercases and splits passwords into two 7-char halves with a fixed DES key; catastrophically weak by design and deprecated since Windows Vista.",
        "common_usage": ["legacy Windows SAM (pre-Vista / compatibility)"],
        "recommended_attack": ["rainbow_table", "mask_attack", "wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- NTLM ----
    1000: {
        "category": "windows",
        "john_format": "nt",
        "length": 32,
        "min_length": 32,
        "max_length": 32,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{32}$",
        "salted": False,
        "security_level": "low",
        "description": "MD4 of the UTF-16LE password. No salt. Used for local Windows account authentication (SAM) and as a component of NetNTLM challenge/response.",
        "common_usage": ["Windows SAM", "Active Directory (NTDS.dit)", "pass-the-hash"],
        "recommended_attack": ["wordlist+rules", "mask_attack", "rainbow_table"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- NetNTLMv1 ----
    5500: {
        "category": "windows",
        "john_format": "netntlm",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": None,
        "regex": None,
        "prefixes": [],
        "salted": True,
        "security_level": "low",
        "description": "Challenge/response format captured from SMB/NTLM network authentication (e.g. via Responder). Crackable back to the underlying NTLM/NT hash.",
        "common_usage": ["SMB relay/capture", "Windows network authentication"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- NetNTLMv2 ----
    5600: {
        "category": "windows",
        "john_format": "netntlmv2",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": None,
        "regex": None,
        "salted": True,
        "security_level": "medium",
        "description": "HMAC-MD5 based challenge/response captured from SMB/NTLM network authentication. Stronger than NetNTLMv1 but still crackable offline.",
        "common_usage": ["SMB relay/capture (Responder)", "Windows network authentication"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- bcrypt ----
    3200: {
        "category": "kdf",
        "john_format": "bcrypt",
        "length": None,
        "min_length": 59,
        "max_length": 60,
        "character_set": "base64-bcrypt",
        "regex": r"^\$2[abxy]\$\d{2}\$[./A-Za-z0-9]{53}$",
        "prefixes": ["$2a$", "$2b$", "$2x$", "$2y$"],
        "salted": True,
        "security_level": "high",
        "description": "Blowfish-based adaptive hash with a tunable cost factor and built-in 16-byte salt. Deliberately slow, GPU-resistant relative to raw hashes.",
        "common_usage": ["modern web application password storage", "Unix crypt() on BSD systems"],
        "recommended_attack": ["wordlist+rules", "targeted_mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- scrypt ----
    8900: {
        "category": "kdf",
        "john_format": "scrypt",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": None,
        "regex": None,
        "prefixes": ["SCRYPT:"],
        "salted": True,
        "security_level": "very_high",
        "description": "Memory-hard KDF designed to resist GPU/ASIC cracking via large memory requirements (N/r/p cost parameters).",
        "common_usage": ["cryptocurrency wallets", "modern password storage"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- PBKDF2 (generic HMAC-SHA256 variant) ----
    10900: {
        "category": "kdf",
        "john_format": "pbkdf2-hmac-sha256",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": None,
        "regex": None,
        "salted": True,
        "security_level": "high",
        "description": "PBKDF2 with HMAC-SHA256, iterated. Strength depends heavily on the iteration count used.",
        "common_usage": ["Django (newer)", "LastPass", "many custom auth systems"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    11900: {
        "category": "kdf",
        "john_format": "pbkdf2-hmac-md5",
        "salted": True,
        "security_level": "medium",
        "description": "PBKDF2 with HMAC-MD5.",
        "common_usage": ["some legacy VPN/auth systems"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    12000: {
        "category": "kdf",
        "john_format": "pbkdf2-hmac-sha1",
        "salted": True,
        "security_level": "medium",
        "description": "PBKDF2 with HMAC-SHA1.",
        "common_usage": ["WPA/WPA2 derivation basis", "1Password (older)", "various apps"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    12100: {
        "category": "kdf",
        "john_format": "pbkdf2-hmac-sha512",
        "salted": True,
        "security_level": "high",
        "description": "PBKDF2 with HMAC-SHA512.",
        "common_usage": ["macOS/other OS password storage", "various apps"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- phpass / WordPress ----
    400: {
        "category": "cms",
        "john_format": "phpass",
        "length": None,
        "min_length": 34,
        "max_length": 34,
        "character_set": "base64-phpass",
        "regex": r"^\$[PH]\$[./A-Za-z0-9]{31}$",
        "prefixes": ["$P$", "$H$"],
        "salted": True,
        "security_level": "medium",
        "description": "Portable PHP password hashing framework used by WordPress, phpBB3, and Joomla (MD5 variant). Iterated MD5 with a salt, cost encoded in the first character after the prefix.",
        "common_usage": ["WordPress", "phpBB3", "Joomla"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Unix DES (descrypt) ----
    1500: {
        "category": "unix",
        "john_format": "descrypt",
        "length": 13,
        "min_length": 13,
        "max_length": 13,
        "character_set": "crypt-base64",
        "regex": r"^[./A-Za-z0-9]{13}$",
        "salted": True,
        "security_level": "very_low",
        "description": "Traditional Unix crypt(3) DES hash. 2-character salt, effectively limited to 8 significant password characters. Long obsolete.",
        "common_usage": ["legacy Unix /etc/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- md5crypt ----
    500: {
        "category": "unix",
        "john_format": "md5crypt",
        "length": None,
        "min_length": 34,
        "max_length": 34,
        "character_set": "crypt-base64",
        "regex": r"^\$1\$[./A-Za-z0-9]{0,8}\$[./A-Za-z0-9]{22}$",
        "prefixes": ["$1$"],
        "salted": True,
        "security_level": "low",
        "description": "1000 rounds of salted MD5 (BSD/Linux crypt $1$). Also used by older Cisco IOS 'type 5' passwords.",
        "common_usage": ["legacy Linux /etc/shadow", "Cisco IOS enable secret (type 5)"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- sha256crypt ----
    7400: {
        "category": "unix",
        "john_format": "sha256crypt",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": "crypt-base64",
        "regex": r"^\$5\$(rounds=\d+\$)?[./A-Za-z0-9]{0,16}\$[./A-Za-z0-9]{43}$",
        "prefixes": ["$5$"],
        "salted": True,
        "security_level": "medium",
        "description": "glibc crypt $5$ SHA-256 based hash with a configurable round count (default 5000).",
        "common_usage": ["modern Linux /etc/shadow"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- sha512crypt ----
    1800: {
        "category": "unix",
        "john_format": "sha512crypt",
        "length": None,
        "min_length": None,
        "max_length": None,
        "character_set": "crypt-base64",
        "regex": r"^\$6\$(rounds=\d+\$)?[./A-Za-z0-9]{0,16}\$[./A-Za-z0-9]{86}$",
        "prefixes": ["$6$"],
        "salted": True,
        "security_level": "medium",
        "description": "glibc crypt $6$ SHA-512 based hash with a configurable round count (default 5000). Default password hash on most modern Linux distributions.",
        "common_usage": ["modern Linux /etc/shadow"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- MySQL323 ----
    200: {
        "category": "database",
        "john_format": "mysql",
        "length": 16,
        "min_length": 16,
        "max_length": 16,
        "character_set": "hex",
        "regex": r"^[a-fA-F0-9]{16}$",
        "salted": False,
        "security_level": "very_low",
        "description": "Old MySQL 3.23 password hash. Extremely weak, effectively a 32-bit-ish search space.",
        "common_usage": ["legacy MySQL < 4.1"],
        "recommended_attack": ["mask_attack", "wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- MySQL 4.1/5 ----
    300: {
        "category": "database",
        "john_format": "mysql-sha1",
        "length": 40,
        "min_length": 41,
        "max_length": 41,
        "character_set": "hex",
        "regex": r"^\*?[a-fA-F0-9]{40}$",
        "prefixes": ["*"],
        "salted": False,
        "security_level": "low",
        "description": "SHA1(SHA1(password)) as used by MySQL 4.1+ / MySQL5 PASSWORD().",
        "common_usage": ["MySQL 4.1+", "MariaDB"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- PostgreSQL CRAM (MD5) ----
    11100: {
        "category": "database",
        "john_format": "postgres",
        "salted": True,
        "prefixes": ["$postgres$"],
        "security_level": "low",
        "description": "PostgreSQL MD5 challenge-response authentication hash, salted with the username.",
        "common_usage": ["PostgreSQL authentication capture"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Oracle H: Type ----
    3100: {
        "category": "database",
        "john_format": "oracle",
        "salted": True,
        "security_level": "low",
        "description": "Oracle 7-10g DES-based password hash (username used as salt).",
        "common_usage": ["Oracle Database 7 through 10g"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Oracle T: Type ----
    12300: {
        "category": "database",
        "john_format": "oracle12c",
        "salted": True,
        "security_level": "medium",
        "description": "Oracle Database 12c+ PBKDF2-SHA512 based password verifier.",
        "common_usage": ["Oracle Database 12c and newer"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Kerberos 5 AS-REQ Pre-Auth (etype 23) ----
    7500: {
        "category": "kerberos",
        "john_format": "krb5pa-md5",
        "prefixes": ["$krb5pa$23$"],
        "salted": True,
        "security_level": "medium",
        "description": "Kerberos 5 AS-REQ Pre-Authentication hash, RC4/etype 23. Obtained via network capture or ASREPRoast-style techniques.",
        "common_usage": ["Active Directory Kerberos authentication capture"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Kerberos 5 TGS-REP (etype 23) - "Kerberoasting" ----
    13100: {
        "category": "kerberos",
        "john_format": "krb5tgs",
        "prefixes": ["$krb5tgs$23$"],
        "salted": True,
        "security_level": "medium",
        "description": "Kerberos 5 TGS-REP hash (RC4/etype 23), the format extracted in a Kerberoasting attack against service accounts.",
        "common_usage": ["Active Directory Kerberoasting"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- Kerberos 5 AS-REP (etype 23) - "ASREPRoasting" ----
    18200: {
        "category": "kerberos",
        "john_format": "krb5asrep",
        "prefixes": ["$krb5asrep$23$"],
        "salted": True,
        "security_level": "medium",
        "description": "Kerberos 5 AS-REP hash (RC4/etype 23) obtained from accounts with Kerberos pre-authentication disabled (ASREPRoasting).",
        "common_usage": ["Active Directory ASREPRoasting"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
    # ---- Cisco-IOS type 4 (SHA256) ----
    5700: {
        "category": "network_device",
        "john_format": "cisco4",
        "salted": False,
        "security_level": "low",
        "description": "Unsalted single-round SHA-256 of the password, base64-encoded. Cisco's original 'type 4' implementation omitted salting/iteration, a known weakness later fixed by 'type 8/9'.",
        "common_usage": ["older Cisco IOS 'enable secret' with type 4 (deprecated by Cisco)"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Cisco-IOS $8$ PBKDF2-SHA256 ----
    9200: {
        "category": "network_device",
        "john_format": "cisco8",
        "prefixes": ["$8$"],
        "salted": True,
        "security_level": "medium",
        "description": "Cisco IOS 'type 8' password: PBKDF2-HMAC-SHA256 with 20,000 iterations.",
        "common_usage": ["Cisco IOS 'enable secret' type 8"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Cisco-IOS $9$ scrypt ----
    9300: {
        "category": "network_device",
        "john_format": "cisco9",
        "prefixes": ["$9$"],
        "salted": True,
        "security_level": "high",
        "description": "Cisco IOS 'type 9' password: scrypt-based, memory-hard KDF.",
        "common_usage": ["Cisco IOS 'enable secret' type 9"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Cisco-PIX / ASA MD5 ----
    2400: {
        "category": "network_device",
        "john_format": "pix-md5",
        "salted": False,
        "security_level": "low",
        "description": "Cisco PIX truncated/salted-with-username MD5 hash.",
        "common_usage": ["Cisco PIX firewall passwords"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    2410: {
        "category": "network_device",
        "john_format": "asa-md5",
        "salted": True,
        "security_level": "low",
        "description": "Cisco ASA MD5 password hash, salted by username.",
        "common_usage": ["Cisco ASA firewall passwords"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- WPA/WPA2 (EAPOL-PBKDF2) ----
    2500: {
        "category": "wireless",
        "john_format": "wpapsk",
        "salted": True,
        "security_level": "medium",
        "description": "WPA/WPA2 4-way handshake, PBKDF2-HMAC-SHA1 keyed by SSID over 4096 iterations. Requires a captured handshake (.hccapx/.pcap), not a plain text hash string.",
        "common_usage": ["Wi-Fi WPA/WPA2-Personal network capture"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/WiFi-WPA"],
    },
    16800: {
        "category": "wireless",
        "john_format": "wpapsk-pmkid",
        "salted": True,
        "security_level": "medium",
        "description": "WPA/WPA2 PMKID hash, derived without needing a full 4-way handshake capture (clientless attack).",
        "common_usage": ["Wi-Fi WPA/WPA2-Personal PMKID capture"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/WiFi-WPA"],
    },
    # ---- Drupal7 ----
    7900: {
        "category": "cms",
        "john_format": "drupal7",
        "prefixes": ["$S$"],
        "salted": True,
        "security_level": "medium",
        "description": "Drupal 7 password hash: iterated salted SHA-512, phpass-style encoding.",
        "common_usage": ["Drupal 7 CMS"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- Django PBKDF2-SHA256 ----
    10000: {
        "category": "cms",
        "john_format": "django",
        "prefixes": ["pbkdf2_sha256$"],
        "salted": True,
        "security_level": "high",
        "description": "Django's default password hasher: PBKDF2-HMAC-SHA256 with a configurable iteration count.",
        "common_usage": ["Django web framework"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- MS Office 2013 (also representative of 2007/2010 family) ----
    9600: {
        "category": "office_document",
        "john_format": "office",
        "prefixes": ["$office$"],
        "salted": True,
        "security_level": "high",
        "description": "Microsoft Office 2013+ document encryption: SHA-512 based, 100,000 iterations of AES key derivation.",
        "common_usage": ["Password-protected .docx/.xlsx/.pptx files"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    9400: {
        "category": "office_document",
        "john_format": "office",
        "prefixes": ["$office$"],
        "salted": True,
        "security_level": "medium",
        "description": "Microsoft Office 2007 document encryption: SHA-1 based, 50,000 iterations of AES key derivation.",
        "common_usage": ["Password-protected Office 2007 documents"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    9500: {
        "category": "office_document",
        "john_format": "office",
        "prefixes": ["$office$"],
        "salted": True,
        "security_level": "medium",
        "description": "Microsoft Office 2010 document encryption: SHA-1 based, 100,000 iterations of AES key derivation.",
        "common_usage": ["Password-protected Office 2010 documents"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- PDF ----
    10400: {
        "category": "document",
        "john_format": "pdf",
        "prefixes": ["$pdf$"],
        "salted": True,
        "security_level": "low",
        "description": "PDF 1.1-1.3 (Acrobat 2-4) standard security handler, RC4-40.",
        "common_usage": ["Password-protected legacy PDF files"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    10500: {
        "category": "document",
        "john_format": "pdf",
        "prefixes": ["$pdf$"],
        "salted": True,
        "security_level": "low",
        "description": "PDF 1.4-1.6 (Acrobat 5-8) standard security handler, RC4-128.",
        "common_usage": ["Password-protected PDF files"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- RAR3 / RAR5 ----
    12500: {
        "category": "archive",
        "john_format": "rar",
        "prefixes": ["$RAR3$"],
        "salted": True,
        "security_level": "medium",
        "description": "RAR3 'header-protected' (-hp) archive password hash, iterated SHA-1.",
        "common_usage": ["Password-protected RAR3 archives"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    13000: {
        "category": "archive",
        "john_format": "rar5",
        "prefixes": ["$rar5$"],
        "salted": True,
        "security_level": "high",
        "description": "RAR5 archive password hash, PBKDF2-HMAC-SHA256 based.",
        "common_usage": ["Password-protected RAR5 archives"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- 7-Zip ----
    11600: {
        "category": "archive",
        "john_format": "7z",
        "salted": True,
        "security_level": "high",
        "description": "7-Zip archive password hash, SHA-256 with a large configurable iteration count (default 2^19).",
        "common_usage": ["Password-protected .7z archives"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    # ---- WinZip / PKZIP ----
    13600: {
        "category": "archive",
        "john_format": "zip",
        "prefixes": ["$zip2$"],
        "salted": True,
        "security_level": "high",
        "description": "WinZip AES-encrypted archive, PBKDF2-HMAC-SHA1 based.",
        "common_usage": ["Password-protected WinZip (AES) archives"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    17200: {
        "category": "archive",
        "john_format": "pkzip",
        "prefixes": ["$pkzip2$"],
        "salted": False,
        "security_level": "low",
        "description": "Classic PKZIP (ZipCrypto) archive password hash. ZipCrypto is cryptographically weak.",
        "common_usage": ["Password-protected legacy .zip archives (ZipCrypto)"],
        "recommended_attack": ["wordlist+rules", "known_plaintext_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- Domain Cached Credentials (DCC / DCC2) ----
    1100: {
        "category": "windows",
        "john_format": "mscash",
        "salted": True,
        "security_level": "low",
        "description": "Windows Domain Cached Credentials (v1), MD4-based, salted with the username. Lets a domain-joined machine authenticate a user without contacting a DC.",
        "common_usage": ["Windows cached domain logon credentials"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    2100: {
        "category": "windows",
        "john_format": "mscash2",
        "prefixes": ["$DCC2$"],
        "salted": True,
        "security_level": "medium",
        "description": "Windows Domain Cached Credentials v2, PBKDF2-HMAC-SHA1 (10,240 rounds) based, salted with the username.",
        "common_usage": ["Windows cached domain logon credentials"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- Radmin2 ----
    9900: {
        "category": "network_protocol",
        "john_format": "radmin",
        "salted": False,
        "security_level": "very_low",
        "description": "Radmin 2.x remote-admin tool password hash.",
        "common_usage": ["Radmin remote administration software"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- BSDi Crypt ----
    12400: {
        "category": "unix",
        "john_format": "bsdicrypt",
        "salted": True,
        "security_level": "very_low",
        "description": "Extended DES-based crypt(3) used historically by BSDi Unix. Adds an iteration count over traditional descrypt.",
        "common_usage": ["legacy BSDi Unix /etc/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- RACF ----
    8500: {
        "category": "unix",
        "john_format": "racf",
        "prefixes": ["$racf$"],
        "salted": True,
        "security_level": "low",
        "description": "IBM z/OS RACF (mainframe security manager) password hash, DES-based.",
        "common_usage": ["IBM z/OS RACF user database"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- AIX password hash family ----
    6300: {
        "category": "unix",
        "john_format": "aix-smd5",
        "prefixes": ["{smd5}"],
        "salted": True,
        "security_level": "low",
        "description": "AIX 'smd5' password hash, salted MD5 variant used in AIX /etc/security/passwd.",
        "common_usage": ["IBM AIX /etc/security/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    6400: {
        "category": "unix",
        "john_format": "aix-ssha256",
        "prefixes": ["{ssha256}"],
        "salted": True,
        "security_level": "medium",
        "description": "AIX 'ssha256' salted SHA-256 password hash.",
        "common_usage": ["IBM AIX /etc/security/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    6500: {
        "category": "unix",
        "john_format": "aix-ssha512",
        "prefixes": ["{ssha512}"],
        "salted": True,
        "security_level": "medium",
        "description": "AIX 'ssha512' salted SHA-512 password hash.",
        "common_usage": ["IBM AIX /etc/security/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },
    6700: {
        "category": "unix",
        "john_format": "aix-ssha1",
        "prefixes": ["{ssha1}"],
        "salted": True,
        "security_level": "low",
        "description": "AIX 'ssha1' salted SHA-1 password hash.",
        "common_usage": ["IBM AIX /etc/security/passwd"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- FortiGate ----
    7000: {
        "category": "network_device",
        "john_format": "fortigate",
        "prefixes": ["AK1"],
        "salted": True,
        "security_level": "low",
        "description": "FortiGate/FortiOS firewall password hash, SHA-1 based with the literal 'AK1' marker prefix.",
        "common_usage": ["Fortinet FortiGate firewall configuration backups"],
        "recommended_attack": ["wordlist+rules", "mask_attack"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- Bitcoin/Litecoin wallet.dat ----
    11300: {
        "category": "cryptocurrency",
        "john_format": "bitcoin",
        "prefixes": ["$bitcoin$"],
        "salted": True,
        "security_level": "high",
        "description": "Bitcoin/Litecoin Core wallet.dat master-key hash, AES-encrypted key protected by SHA-512-based key stretching.",
        "common_usage": ["Bitcoin Core / Litecoin Core wallet.dat files"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- KeePass ----
    13400: {
        "category": "application",
        "john_format": "keepass",
        "prefixes": ["$keepass$"],
        "salted": True,
        "security_level": "high",
        "description": "KeePass 1.x/2.x database master-key hash (AES or Twofish, PBKDF2/AES-based key stretching, optionally combined with a keyfile).",
        "common_usage": ["KeePass password manager database files"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt"],
    },

    # ---- JWT (structural marker only, not a password KDF) ----
    16500: {
        "category": "network_protocol",
        "john_format": None,
        "prefixes": ["eyJ"],
        "salted": False,
        "security_level": None,
        "description": "JSON Web Token. The 'eyJ' prefix is the base64 encoding of '{\"' and appears at the start of essentially every JWT header. Attacking a JWT means recovering the HMAC secret, not a traditional password hash.",
        "common_usage": ["Web API authentication tokens"],
        "recommended_attack": ["wordlist+rules"],
        "recommended_wordlists": ["rockyou.txt", "SecLists/Passwords/Common-Credentials"],
    },
}
